-- ============================================================
-- KE built-in exercise library (bilingual EN/中文)
-- INSERT OR IGNORE => reseeding never overwrites user data.
-- Columns: slug, name_en, name_zh, equipment, category, pattern,
--          primary_muscles, secondary_muscles  (CSV muscle lists)
-- ============================================================

-- ============ BARBELL (60) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('bb-back-squat','Barbell Back Squat','杠铃颈后深蹲','barbell','compound','squat','quads','glutes,core,adductors'),
('bb-front-squat','Barbell Front Squat','杠铃颈前深蹲','barbell','compound','squat','quads','glutes,core,upper-back'),
('bb-low-bar-squat','Barbell Low-Bar Squat','杠铃低位深蹲','barbell','compound','squat','glutes','quads,hamstrings,core'),
('bb-box-squat','Barbell Box Squat','杠铃箱式深蹲','barbell','compound','squat','quads','glutes,hamstrings'),
('bb-pause-squat','Barbell Pause Squat','杠铃暂停深蹲','barbell','compound','squat','quads','glutes,core'),
('bb-bulgarian-split-squat-bb','Barbell Bulgarian Split Squat','杠铃保加利亚分腿蹲','barbell','compound','single-leg','quads','glutes,hamstrings'),
('bb-lunge','Barbell Lunge','杠铃箭步蹲','barbell','compound','single-leg','quads','glutes,hamstrings'),
('bb-walking-lunge','Barbell Walking Lunge','杠铃行走箭步蹲','barbell','compound','single-leg','quads','glutes'),
('bb-step-up-bb','Barbell Step-up','杠铃登台阶','barbell','compound','single-leg','quads','glutes'),
('bb-zercher-squat','Barbell Zercher Squat','杠铃泽奇深蹲','barbell','compound','squat','quads','core,glutes'),
('bb-hack-squat-bb','Barbell Hack Squat','杠铃哈克深蹲','barbell','compound','squat','quads','glutes'),
('bb-sumo-deadlift','Barbell Sumo Deadlift','杠铃相扑硬拉','barbell','compound','hinge','glutes','hamstrings,quads,core,upper-back'),
('bb-conventional-deadlift','Barbell Conventional Deadlift','杠铃传统硬拉','barbell','compound','hinge','hamstrings','glutes,core,upper-back,quads'),
('bb-romanian-deadlift','Barbell Romanian Deadlift','杠铃罗马尼亚硬拉','barbell','compound','hinge','hamstrings','glutes,core'),
('bb-stiff-leg-deadlift','Barbell Stiff-Leg Deadlift','杠铃直腿硬拉','barbell','compound','hinge','hamstrings','glutes,core'),
('bb-single-leg-rdl','Barbell Single-Leg RDL','杠铃单腿罗马尼亚硬拉','barbell','compound','hinge','hamstrings','glutes,core'),
('bb-deficit-deadlift','Barbell Deficit Deadlift','杠铃赤字硬拉','barbell','compound','hinge','hamstrings','glutes,core,upper-back'),
('bb-rack-pull','Barbell Rack Pull','杠铃架上拉','barbell','compound','hinge','upper-back','hamstrings,glutes,forearms'),
('bb-good-morning','Barbell Good Morning','杠铃早安式体前屈','barbell','compound','hinge','hamstrings','glutes,core'),
('bb-hip-thrust','Barbell Hip Thrust','杠铃臀桥（臀推）','barbell','isolation','hinge','glutes','hamstrings'),
('bb-glute-bridge-bb','Barbell Glute Bridge','杠铃臀桥','barbell','isolation','hinge','glutes','hamstrings'),
('bb-power-clean','Barbell Power Clean','杠铃高翻','barbell','olympic','hinge','upper-back','quads,glutes,hamstrings,forearms'),
('bb-squat-clean','Barbell Squat Clean','杠铃下蹲翻','barbell','olympic','hinge','quads','upper-back,glutes,hamstrings'),
('bb-hang-clean','Barbell Hang Clean','杠铃悬垂翻','barbell','olympic','hinge','upper-back','quads,glutes,forearms'),
('bb-clean-and-jerk','Barbell Clean and Jerk','杠铃挺举','barbell','olympic','full-body','quads','shoulders,glutes,hamstrings,core'),
('bb-snatch','Barbell Snatch','杠铃抓举','barbell','olympic','full-body','quads','shoulders,glutes,hamstrings,core'),
('bb-hang-snatch','Barbell Hang Snatch','杠铃悬垂抓举','barbell','olympic','full-body','quads','shoulders,hamstrings,core'),
('bb-power-snatch','Barbell Power Snatch','杠铃高抓','barbell','olympic','full-body','quads','shoulders,glutes,core'),
('bb-push-press','Barbell Push Press','杠铃借力推举','barbell','compound','press','shoulders','triceps,quads,core'),
('bb-overhead-press','Barbell Overhead Press','杠铃站姿推举','barbell','compound','press','shoulders','triceps,core'),
('bb-seated-behind-neck-press','Barbell Seated Behind-the-Neck Press','杠铃坐姿颈后推举','barbell','compound','press','shoulders','triceps,upper-back'),
('bb-bench-press','Barbell Bench Press','杠铃卧推','barbell','compound','press','chest','triceps,front-delts'),
('bb-incline-bench-press','Barbell Incline Bench Press','杠铃上斜卧推','barbell','compound','press','chest','front-delts,triceps'),
('bb-decline-bench-press','Barbell Decline Bench Press','杠铃下斜卧推','barbell','compound','press','chest','triceps'),
('bb-close-grip-bench-press','Barbell Close-Grip Bench Press','杠铃窄距卧推','barbell','compound','press','triceps','chest,front-delts'),
('bb-floor-press','Barbell Floor Press','杠铃地板卧推','barbell','compound','press','triceps','chest,front-delts'),
('bb-spoto-press','Barbell Spoto Press','杠铃斯波托卧推','barbell','compound','press','chest','triceps'),
('bb-board-press','Barbell Board Press','杠铃木板卧推','barbell','compound','press','triceps','chest'),
('bb-landmine-press-bb','Landmine Overhead Press','地雷架推举','barbell','compound','press','shoulders','chest,core'),
('bb-landmine-row','Landmine Row','地雷架划船','barbell','compound','pull','upper-back','lats,biceps'),
('bb-t-bar-row','Barbell T-Bar Row','杠铃T杆划船','barbell','compound','pull','upper-back','lats,biceps'),
('bb-bent-over-row','Barbell Bent-Over Row','杠铃俯身划船','barbell','compound','pull','upper-back','lats,biceps,core'),
('bb-pannatta-row','Barbell Pendlay Row','杠铃潘德雷划船','barbell','compound','pull','upper-back','lats,biceps,hamstrings'),
('bb-yates-row','Barbell Yates Row','杠铃耶茨划船','barbell','compound','pull','lats','upper-back,biceps'),
('bb-single-arm-landmine-row','Single-Arm Landmine Row','单臂地雷架划船','barbell','compound','pull','lats','upper-back,biceps'),
('bb-meadows-row','Meadows Row','米多斯划船','barbell','compound','pull','lats','upper-back,biceps'),
('bb-landmine-twist','Landmine Twist','地雷架转体','barbell','isolation','rotation','obliques','core'),
('bb-landmine-lateral-raise','Landmine Lateral Raise','地雷架侧平举','barbell','isolation','press','side-delts',''),
('bb-curl','Barbell Curl','杠铃弯举','barbell','isolation','pull','biceps','forearms'),
('bb-wide-grip-curl','Barbell Wide-Grip Curl','杠铃宽握弯举','barbell','isolation','pull','biceps',''),
('bb-close-grip-curl','Barbell Close-Grip Curl','杠铃窄握弯举','barbell','isolation','pull','biceps',''),
('bb-reverse-curl','Barbell Reverse Curl','杠铃反握弯举','barbell','isolation','pull','forearms','biceps'),
('bb-wrist-curl','Barbell Wrist Curl','杠铃腕弯举','barbell','isolation','pull','forearms',''),
('bb-reverse-wrist-curl','Barbell Reverse Wrist Curl','杠铃反握腕弯举','barbell','isolation','pull','forearms',''),
('bb-preacher-curl','Barbell Preacher Curl','杠铃牧师凳弯举','barbell','isolation','pull','biceps',''),
('bb-skullcrusher','Barbell Skullcrusher','杠铃仰卧臂屈伸','barbell','isolation','press','triceps',''),
('bb-close-grip-skullcrusher','Barbell Close-Grip Skullcrusher','杠铃窄距仰卧臂屈伸','barbell','isolation','press','triceps',''),
('bb-overhead-triceps-extension-bb','Barbell Overhead Triceps Extension','杠铃头顶臂屈伸','barbell','isolation','press','triceps',''),
('bb-upright-row','Barbell Upright Row','杠铃直立划船','barbell','isolation','pull','side-delts','traps,biceps'),
('bb-shrug','Barbell Shrug','杠铃耸肩','barbell','isolation','pull','traps','forearms'),
('bb-behind-back-shrug','Barbell Behind-the-Back Shrug','杠铃背后耸肩','barbell','isolation','pull','traps',''),
('bb-calf-raise-bb','Barbell Calf Raise','杠铃提踵','barbell','isolation','squat','calves','');

-- ============ DUMBBELL (50) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('db-bench-press','Dumbbell Bench Press','哑铃卧推','dumbbell','compound','press','chest','triceps,front-delts'),
('db-incline-bench-press','Dumbbell Incline Bench Press','哑铃上斜卧推','dumbbell','compound','press','chest','front-delts,triceps'),
('db-decline-bench-press','Dumbbell Deline Bench Press','哑铃下斜卧推','dumbbell','compound','press','chest','triceps'),
('db-floor-press','Dumbbell Floor Press','哑铃地板卧推','dumbbell','compound','press','chest','triceps'),
('db-flye','Dumbbell Flye','哑铃飞鸟','dumbbell','isolation','press','chest',''),
('db-incline-flye','Dumbbell Incline Flye','哑铃上斜飞鸟','dumbbell','isolation','press','chest',''),
('db-cable-crossover-db-version','Dumbbell Svend Press','哑铃斯文德推胸','dumbbell','isolation','press','chest',''),
('db-shoulder-press','Dumbbell Shoulder Press','哑铃肩上推举','dumbbell','compound','press','shoulders','triceps,core'),
('db-arnold-press','Dumbbell Arnold Press','阿诺德推举','dumbbell','compound','press','shoulders','triceps'),
('db-seated-shoulder-press','Dumbbell Seated Shoulder Press','哑铃坐姿推举','dumbbell','compound','press','shoulders','triceps'),
('db-lateral-raise','Dumbbell Lateral Raise','哑铃侧平举','dumbbell','isolation','press','side-delts',''),
('db-lean-away-lateral-raise','Dumbbell Lean-Away Lateral Raise','哑铃侧倾侧平举','dumbbell','isolation','press','side-delts',''),
('db-front-raise','Dumbbell Front Raise','哑铃前平举','dumbbell','isolation','press','front-delts',''),
('db-rear-delt-row','Dumbbell Rear Delt Row','哑铃俯身划船（后束）','dumbbell','isolation','pull','rear-delts','upper-back'),
('db-rear-delt-flye','Dumbbell Rear Delt Flye','哑铃俯身飞鸟（后束）','dumbbell','isolation','pull','rear-delts','upper-back'),
('db-upright-row-db','Dumbbell Upright Row','哑铃直立划船','dumbbell','isolation','pull','side-delts','traps'),
('db-shrug','Dumbbell Shrug','哑铃耸肩','dumbbell','isolation','pull','traps','forearms'),
('db-single-arm-row','Dumbbell Single-Arm Row','哑铃单臂划船','dumbbell','compound','pull','lats','upper-back,biceps'),
('db-single-arm-row-on-bench','Dumbbell Row on Bench','哑铃斜托单臂划船','dumbbell','compound','pull','lats','upper-back,biceps'),
('db-renegade-row','Dumbbell Renegade Row','哑铃叛徒划船','dumbbell','compound','pull','lats','core,upper-back'),
('db-seal-row-db','Dumbbell Seal Row','哑铃海豹划船','dumbbell','compound','pull','upper-back','lats,biceps'),
('db-incline-row','Dumpbell Incline Row','哑铃上斜划船','dumbbell','compound','pull','upper-back','lats,biceps'),
('db-chest-supported-row','Dumbbell Chest-Supported Incline Row','哑铃上斜板划船','dumbbell','compound','pull','upper-back','lats,biceps'),
('db-pullover','Dumbbell Pullover','哑铃仰卧上拉','dumbbell','isolation','pull','lats','chest'),
('db-curl','Dumbbell Curl','哑铃弯举','dumbbell','isolation','pull','biceps','forearms'),
('db-hammer-curl','Dumbbell Hammer Curl','哑铃锤式弯举','dumbbell','isolation','pull','biceps','forearms'),
('db-incline-curl','Dumbbell Incline Curl','哑铃上斜弯举','dumbbell','isolation','pull','biceps',''),
('db-preacher-curl-db','Dumbbell Preacher Curl','哑铃牧师凳弯举','dumbbell','isolation','pull','biceps',''),
('db-concentration-curl','Dumbbell Concentration Curl','哑铃集中弯举','dumbbell','isolation','pull','biceps',''),
('db-spider-curl','Dumbbell Spider Curl','哑铃蜘蛛弯举','dumbbell','isolation','pull','biceps',''),
('db-zottman-curl','Dumbbell Zottman Curl','哑铃佐特曼弯举','dumbbell','isolation','pull','biceps','forearms'),
('db-cross-body-hammer-curl','Dumbbell Cross-Body Hammer Curl','哑铃交叉锤式弯举','dumbbell','isolation','pull','biceps','forearms'),
('db-reverse-curl-db','Dumbbell Reverse Curl','哑铃反握弯举','dumbbell','isolation','pull','forearms','biceps'),
('db-wrist-curl-db','Dumbbell Wrist Curl','哑铃腕弯举','dumbbell','isolation','pull','forearms',''),
('db-skullcrusher-db','Dumbbell Skullcrusher','哑铃仰卧臂屈伸','dumbbell','isolation','press','triceps',''),
('db-overhead-triceps-extension','Dumbbell Overhead Triceps Extension','哑铃头顶臂屈伸','dumbbell','isolation','press','triceps',''),
('db-kickback','Dumbbell Kickback','哑铃俯身臂屈伸','dumbbell','isolation','press','triceps',''),
('db-jm-press','Dumbbell JM Press','哑铃JM推举','dumbbell','isolation','press','triceps',''),
('db-single-arm-triceps-extension','Dumbbell Single-Arm Triceps Extension','哑铃单臂头顶臂屈伸','dumbbell','isolation','press','triceps',''),
('db-goblet-squat','Dumbbell Goblet Squat','哑铃高脚杯深蹲','dumbbell','compound','squat','quads','glutes,core'),
('db-front-squat-db','Dumbbell Front Squat','哑铃前蹲','dumbbell','compound','squat','quads','glutes,core'),
('db-bulgarian-split-squat-db','Dumbbell Bulgarian Split Squat','哑铃保加利亚分腿蹲','dumbbell','compound','single-leg','quads','glutes'),
('db-lunge-db','Dumbbell Lunge','哑铃箭步蹲','dumbbell','compound','single-leg','quads','glutes'),
('db-walking-lunge-db','Dumbbell Walking Lunge','哑铃行走箭步蹲','dumbbell','compound','single-leg','quads','glutes'),
('db-reverse-lunge','Dumbbell Reverse Lunge','哑铃后箭步蹲','dumbbell','compound','single-leg','quads','glutes'),
('db-step-up-db','Dumbbell Step-up','哑铃登台阶','dumbbell','compound','single-leg','quads','glutes'),
('db-single-leg-rdl-db','Dumbbell Single-Leg RDL','哑铃单腿罗马尼亚硬拉','dumbbell','compound','hinge','hamstrings','glutes,core'),
('db-rdl-db','Dumbbell Romanian Deadlift','哑铃罗马尼亚硬拉','dumbbell','compound','hinge','hamstrings','glutes'),
('db-sumo-squat-db','Dumbbell Sumo Squat','哑铃相扑深蹲','dumbbell','compound','squat','quads','glutes,adductors'),
('db-calf-raise-db','Dumbbell Calf Raise','哑铃提踵','dumbbell','isolation','squat','calves',''),
('db-single-leg-calf-raise','Dumbbell Single-Leg Calf Raise','哑铃单腿提踵','dumbbell','isolation','squat','calves',''),
('db-farmer-walk','Dumbbell Farmers Walk','哑铃农夫行走','dumbbell','compound','carry','forearms','traps,core'),
('db-turkish-get-up','Dumbbell Turkish Get-up','哑铃土耳其起立','dumbbell','compound','full-body','core','shoulders,glutes');

-- ============ EZ-BAR (12) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('ez-curl','EZ-Bar Curl','曲杆弯举','ez-bar','isolation','pull','biceps','forearms'),
('ez-wide-grip-curl','EZ-Bar Wide-Grip Curl','曲杆宽握弯举','ez-bar','isolation','pull','biceps',''),
('ez-close-grip-curl','EZ-Bar Close-Grip Curl','曲杆窄握弯举','ez-bar','isolation','pull','biceps',''),
('ez-reverse-curl','EZ-Bar Reverse Curl','曲杆反握弯举','ez-bar','isolation','pull','forearms',''),
('ez-skullcrusher','EZ-Bar Skullcrusher','曲杆仰卧臂屈伸','ez-bar','isolation','press','triceps',''),
('ez-overhead-triceps-extension','EZ-Bar Overhead Triceps Extension','曲杆头顶臂屈伸','ez-bar','isolation','press','triceps',''),
('ez-upright-row','EZ-Bar Upright Row','曲杆直立划船','ez-bar','isolation','pull','side-delts','traps'),
('ez-preacher-curl','EZ-Bar Preacher Curl','曲杆牧师凳弯举','ez-bar','isolation','pull','biceps',''),
('ez-spider-curl','EZ-Bar Spider Curl','曲杆蜘蛛弯举','ez-bar','isolation','pull','biceps',''),
('ez-bent-over-row','EZ-Bar Bent-Over Row','曲杆俯身划船','ez-bar','compound','pull','upper-back','lats,biceps'),
('ez-seated-row','EZ-Bar Seated Row','曲杆坐姿划船','ez-bar','compound','pull','upper-back','lats,biceps'),
('ez-shrug','EZ-Bar Shrug','曲杆耸肩','ez-bar','isolation','pull','traps','');

-- ============ KETTLEBELL (20) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('kb-swing','Kettlebell Swing','壶铃摇摆','kettlebell','compound','hinge','glutes','hamstrings,core'),
('kb-goblet-squat','Kettlebell Goblet Squat','壶铃高脚杯深蹲','kettlebell','compound','squat','quads','glutes,core'),
('kb-front-squat','Kettlebell Front Squat','壶铃前蹲','kettlebell','compound','squat','quads','core,glutes'),
('kb-sumo-deadlift-high-pull','Kettlebell Sumo Deadlift High Pull','壶铃相扑硬拉高拉','kettlebell','compound','hinge','quads','upper-back,glutes'),
('kb-single-arm-row-kb','Kettlebell Single-Arm Row','壶铃单臂划船','kettlebell','compound','pull','lats','upper-back,biceps'),
('kb-clean','Kettlebell Clean','壶铃翻壶','kettlebell','compound','hinge','glutes','shoulders,hamstrings'),
('kb-snatch-kb','Kettlebell Snatch','壶铃抓举','kettlebell','compound','full-body','glutes','shoulders,hamstrings,core'),
('kb-press','Kettlebell Single-Arm Press','壶铃单臂推举','kettlebell','compound','press','shoulders','triceps,core'),
('kb-push-press-kb','Kettlebell Push Press','壶铃借力推举','kettlebell','compound','press','shoulders','triceps,quads'),
('kb-turkish-get-up','Kettlebell Turkish Get-up','壶铃土耳其起立','kettlebell','compound','full-body','core','shoulders,glutes'),
('kb-windmill','Kettlebell Windmill','壶铃风车','kettlebell','isolation','press','obliques','shoulders'),
('kb-halo','Kettlebell Halo','壶铃光环绕肩','kettlebell','isolation','press','shoulders','core'),
('kb-single-leg-rdl-kb','Kettlebell Single-Leg RDL','壶铃单腿罗马尼亚硬拉','kettlebell','compound','hinge','hamstrings','glutes,core'),
('kb-cossack-squat','Kettlebell Cossack Squat','壶铃哥萨克深蹲','kettlebell','compound','single-leg','adductors','quads,glutes'),
('kb-lunge-press','Kettlebell Lunge Press','壶铃箭步蹲推举','kettlebell','compound','full-body','quads','shoulders,glutes,core'),
('kb-farmer-carry','Kettlebell Farmer Carry','壶铃农夫行走','kettlebell','compound','carry','forearms','traps,core'),
('kb-suitcase-carry','Kettlebell Suitcase Carry','壶铃手提箱行走','kettlebell','compound','carry','core','obliques,forearms'),
('kb-figure-8','Kettlebell Figure-8','壶铃8字绕身','kettlebell','isolation','rotation','core','obliques'),
('kb-russian-twist-kb','Kettlebell Russian Twist','壶铃俄罗斯转体','kettlebell','isolation','rotation','obliques','core'),
('kb-calf-raise-kb','Kettlebell Calf Raise','壶铃提踵','kettlebell','isolation','squat','calves','');

-- ============ CABLE (35) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('cb-lat-pulldown','Cable Lat Pulldown','高位下拉','cable','compound','pull','lats','biceps,upper-back'),
('cb-wide-grip-pulldown','Cable Wide-Grip Pulldown','宽握高位下拉','cable','compound','pull','lats','biceps,upper-back'),
('cb-close-grip-pulldown','Cable Close-Grip Pulldown','窄握高位下拉','cable','compound','pull','lats','biceps'),
('cb-neutral-grip-pulldown','Cable Neutral-Grip Pulldown','对握高位下拉','cable','compound','pull','lats','biceps'),
('cb-single-arm-pulldown','Cable Single-Arm Pulldown','单臂高位下拉','cable','compound','pull','lats','biceps'),
('cb-straight-arm-pulldown','Cable Straight-Arm Pulldown','直臂下拉','cable','isolation','pull','lats','core'),
('cb-seated-row','Cable Seated Row','坐姿划船','cable','compound','pull','upper-back','lats,biceps'),
('cb-seated-row-wide','Cable Wide-Grip Seated Row','宽握坐姿划船','cable','compound','pull','upper-back','lats,biceps'),
('cb-seated-row-close','Cable Close-Grip Seated Row','窄握坐姿划船','cable','compound','pull','lats','biceps'),
('cb-single-arm-seated-row','Cable Single-Arm Seated Row','单臂坐姿划船','cable','compound','pull','lats','upper-back,biceps'),
('cb-face-pull','Cable Face Pull','面拉','cable','isolation','pull','rear-delts','upper-back,traps'),
('cb-crossover','Cable Crossover','龙门架夹胸','cable','isolation','press','chest','front-delts'),
('cb-low-to-high-crossover','Cable Low-to-High Flye','低位夹胸（上）','cable','isolation','press','chest','front-delts'),
('cb-high-to-low-crossover','Cable High-to-Low Flye','高位夹胸（下）','cable','isolation','press','chest','front-delts'),
('cb-single-arm-crossover','Cable Single-Arm Crossover','单臂夹胸','cable','isolation','press','chest',''),
('cb-triceps-pushdown','Cable Triceps Pushdown','绳索下压','cable','isolation','press','triceps',''),
('cb-rope-pushdown','Cable Rope Pushdown','绳索（绳把）下压','cable','isolation','press','triceps',''),
('cb-reverse-grip-pushdown','Cable Reverse-Grip Pushdown','反握下压','cable','isolation','press','triceps',''),
('cb-overhead-rope-extension','Cable Overhead Rope Extension','绳索头顶臂屈伸','cable','isolation','press','triceps',''),
('cb-single-arm-pushdown','Cable Single-Arm Pushdown','单臂下压','cable','isolation','press','triceps',''),
('cb-cable-curl','Cable Curl','绳索弯举','cable','isolation','pull','biceps','forearms'),
('cb-rope-hammer-curl','Cable Rope Hammer Curl','绳索锤式弯举','cable','isolation','pull','biceps','forearms'),
('cb-reverse-grip-curl-cable','Cable Reverse-Grip Curl','绳索反握弯举','cable','isolation','pull','forearms',''),
('cb-concentration-curl-cable','Cable Concentration Curl','绳索集中弯举','cable','isolation','pull','biceps',''),
('cb-woodchop','Cable Woodchop','绳索伐木','cable','compound','rotation','obliques','core'),
('cb-russian-twist-cable','Cable Russian Twist','绳索俄罗斯转体','cable','isolation','rotation','obliques','core'),
('cb-pallof-press','Cable Pallof Press','帕洛夫推举','cable','isolation','rotation','core','obliques'),
('cb-crunch-cable','Cable Crunch','绳索卷腹','cable','isolation','rotation','abs','obliques'),
('cb-lateral-raise-cable','Cable Lateral Raise','绳索侧平举','cable','isolation','press','side-delts',''),
('cb-front-raise-cable','Cable Front Raise','绳索前平举','cable','isolation','press','front-delts',''),
('cb-rear-delt-flye-cable','Cable Rear Delt Flye','绳索后束飞鸟','cable','isolation','pull','rear-delts','upper-back'),
('cb-upright-row-cable','Cable Upright Row','绳索直立划船','cable','isolation','pull','side-delts','traps'),
('cb-pull-through','Cable Pull-Through','绳索跨拉','cable','compound','hinge','glutes','hamstrings'),
('cb-cable-kickback','Cable Glute Kickback','绳索后踢腿','cable','isolation','hinge','glutes','hamstrings'),
('cb-cable-hip-abduction','Cable Hip Abduction','绳索髋外展','cable','isolation','squat','glutes','adductors');

-- ============ MACHINE (40) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('mc-chest-press','Machine Chest Press','坐姿推胸器','machine','compound','press','chest','triceps,front-delts'),
('mc-incline-chest-press','Machine Incline Chest Press','上斜推胸器','machine','compound','press','chest','front-delts,triceps'),
('mc-pec-deck','Pec Deck Flye','蝴蝶机夹胸','machine','isolation','press','chest',''),
('mc-chest-flye-machine','Machine Chest Flye','坐姿夹胸器','machine','isolation','press','chest',''),
('mc-shoulder-press-machine','Machine Shoulder Press','坐姿推肩器','machine','compound','press','shoulders','triceps'),
('mc-lateral-raise-machine','Machine Lateral Raise','侧平举机','machine','isolation','press','side-delts',''),
('mc-rear-delt-machine','Machine Rear Delt Flye','后束飞鸟机','machine','isolation','pull','rear-delts','upper-back'),
('mc-lat-pulldown-machine','Machine Lat Pulldown','高位下拉机','machine','compound','pull','lats','biceps'),
('mc-seated-row-machine','Machine Seated Row','坐姿划船机','machine','compound','pull','upper-back','lats,biceps'),
('mc-assisted-pullup','Assisted Pull-up','辅助引体向上','machine','compound','pull','lats','biceps'),
('mc-assisted-dip','Assisted Dip','辅助双杠臂屈伸','machine','compound','press','triceps','chest,front-delts'),
('mc-leg-press','Leg Press','倒蹬机','machine','compound','squat','quads','glutes'),
('mc-hack-squat-machine','Machine Hack Squat','哈克深蹲机','machine','compound','squat','quads','glutes'),
('mc-leg-extension','Leg Extension','腿屈伸','machine','isolation','squat','quads',''),
('mc-lying-leg-curl','Lying Leg Curl','俯卧腿弯举','machine','isolation','hinge','hamstrings','calves'),
('mc-seated-leg-curl','Seated Leg Curl','坐姿腿弯举','machine','isolation','hinge','hamstrings','calves'),
('mc-standing-leg-curl','Standing Leg Curl','站姿腿弯举','machine','isolation','hinge','hamstrings','glutes'),
('mc-hip-thrust-machine','Machine Hip Thrust','臀推机','machine','isolation','hinge','glutes','hamstrings'),
('mc-glute-kickback-machine','Machine Glute Kickback','髋后踢机','machine','isolation','hinge','glutes','hamstrings'),
('mc-hip-abduction-machine','Machine Hip Abduction','髋外展机','machine','isolation','squat','glutes',''),
('mc-hip-adduction-machine','Machine Hip Adduction','髋内收机','machine','isolation','squat','adductors',''),
('mc-calf-raise-machine','Machine Calf Raise','站姿提踵机','machine','isolation','squat','calves',''),
('mc-seated-calf-raise-machine','Machine Seated Calf Raise','坐姿提踵机','machine','isolation','squat','calves',''),
('mc-donkey-calf-raise','Donkey Calf Raise','驴式提踵','machine','isolation','squat','calves',''),
('mc-tibialis-raise','Tibialis Raise','胫骨前肌训练器','machine','isolation','squat','tibialis',''),
('mc-smith-squat-note','Machine Squat (Belt)','负重深蹲机（腰带式）','machine','compound','squat','quads','glutes,core'),
('mc-v-squat','V-Squat Machine','V型深蹲机','machine','compound','squat','quads','glutes'),
('mc-pendulum-squat','Pendulum Squat','摆锤深蹲机','machine','compound','squat','quads','glutes'),
('mc-biceps-curl-machine','Machine Biceps Curl','坐姿弯举机','machine','isolation','pull','biceps',''),
('mc-preacher-curl-machine','Machine Preacher Curl','牧师凳弯举机','machine','isolation','pull','biceps',''),
('mc-triceps-extension-machine','Machine Triceps Extension','坐姿臂屈伸机','machine','isolation','press','triceps',''),
('mc-dip-machine','Machine Dip','双杠臂屈伸机','machine','compound','press','triceps','chest'),
('mc-row-machine-hammer','Hammer Strength Row','悍马划船机','machine','compound','pull','upper-back','lats,biceps'),
('mc-chest-press-hammer','Hammer Strength Chest Press','悍马推胸机','machine','compound','press','chest','triceps'),
('mc-pullover-machine','Pullover Machine','背阔肌上拉机','machine','isolation','pull','lats',''),
('mc-back-extension','Back Extension（罗马椅）','山羊挺身','machine','isolation','hinge','lower-back','glutes,hamstrings'),
('mc-reverse-hyper','Reverse Hyperextension','反向挺身','machine','isolation','hinge','glutes','lower-back,hamstrings'),
('mc-ab-machine','Machine Ab Crunch','坐姿卷腹机','machine','isolation','rotation','abs','obliques'),
('mc-neck-extension','Neck Extension','颈部伸展器','machine','isolation','press','neck','traps');

-- ============ SMITH MACHINE (15) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('sm-squat','Smith Machine Squat','史密斯深蹲','smith','compound','squat','quads','glutes'),
('sm-front-squat','Smith Machine Front Squat','史密斯颈前深蹲','smith','compound','squat','quads','glutes'),
('sm-sumo-squat','Smith Machine Sumo Squat','史密斯相扑深蹲','smith','compound','squat','quads','glutes,adductors'),
('sm-split-squat','Smith Machine Bulgarian Split Squat','史密斯保加利亚分腿蹲','smith','compound','single-leg','quads','glutes'),
('sm-hip-thrust','Smith Machine Hip Thrust','史密斯臀推','smith','isolation','hinge','glutes','hamstrings'),
('sm-rdl','Smith Machine Romanian Deadlift','史密斯罗马尼亚硬拉','smith','compound','hinge','hamstrings','glutes'),
('sm-good-morning','Smith Machine Good Morning','史密斯早安式','smith','compound','hinge','hamstrings','glutes'),
('sm-bench-press','Smith Machine Bench Press','史密斯卧推','smith','compound','press','chest','triceps'),
('sm-incline-bench-press','Smith Machine Incline Bench Press','史密斯上斜卧推','smith','compound','press','chest','front-delts'),
('sm-decline-bench-press','Smith Machine Decline Bench Press','史密斯下斜卧推','smith','compound','press','chest','triceps'),
('sm-shoulder-press','Smith Machine Shoulder Press','史密斯推肩','smith','compound','press','shoulders','triceps'),
('sm-behind-neck-press','Smith Machine Behind-the-Neck Press','史密斯颈后推举','smith','compound','press','shoulders','triceps'),
('sm-bent-over-row','Smith Machine Bent-Over Row','史密斯俯身划船','smith','compound','pull','upper-back','lats,biceps'),
('sm-inverted-row','Smith Machine Inverted Row','史密斯反向划船','smith','compound','pull','upper-back','lats,biceps'),
('sm-calf-raise','Smith Machine Calf Raise','史密斯提踵','smith','isolation','squat','calves','');

-- ============ TRAP BAR / SPECIALTY BAR (6) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('tb-deadlift','Trap Bar Deadlift','六角杠硬拉','trap-bar','compound','hinge','glutes','hamstrings,quads,core,upper-back'),
('tb-jump','Trap Bar Jump','六角杠跳跃','trap-bar','olympic','hinge','quads','glutes,calves'),
('tb-row','Trap Bar Row','六角杠划船','trap-bar','compound','pull','upper-back','lats,biceps'),
('tb-carry','Trap Bar Carry','六角杠行走','trap-bar','compound','carry','forearms','traps,core'),
('tb-squat','Trap Bar Squat','六角杠深蹲','trap-bar','compound','squat','quads','glutes'),
('tb-hip-thrust','Trap Bar Hip Thrust','六角杠臀推','trap-bar','isolation','hinge','glutes','hamstrings');

-- ============ BODYWEIGHT (30) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('bw-pullup','Pull-up','引体向上','bodyweight','compound','pull','lats','biceps,upper-back'),
('bw-chinup','Chin-up','反手引体向上','bodyweight','compound','pull','lats','biceps'),
('bw-neutral-grip-pullup','Neutral-Grip Pull-up','对握引体向上','bodyweight','compound','pull','lats','biceps'),
('bw-commando-pullup','Commando Pull-up','交错握引体向上','bodyweight','compound','pull','lats','biceps,obliques'),
('bw-muscle-up','Muscle-up','双力臂','bodyweight','olympic','pull','lats','chest,triceps,core'),
('bw-pushup','Push-up','俯卧撑','bodyweight','compound','press','chest','triceps,front-delts'),
('bw-wide-pushup','Wide-Grip Push-up','宽距俯卧撑','bodyweight','compound','press','chest','front-delts'),
('bw-diamond-pushup','Diamond Push-up','钻石俯卧撑','bodyweight','compound','press','triceps','chest'),
('bw-decline-pushup','Decline Push-up','下斜俯卧撑（脚垫高）','bodyweight','compound','press','chest','front-delts'),
('bw-archer-pushup','Archer Push-up','射手俯卧撑','bodyweight','compound','press','chest','triceps'),
('bw-pseudo-planche-pushup','Pseudo Planche Push-up','伪俄挺俯卧撑','bodyweight','compound','press','front-delts','chest,triceps'),
('bw-dip','Parallel Bar Dip','双杠臂屈伸','bodyweight','compound','press','triceps','chest,front-delts'),
('bw-bench-dip','Bench Dip','板凳臂屈伸','bodyweight','compound','press','triceps','chest'),
('bw-pike-pushup','Pike Push-up','倒V俯卧撑','bodyweight','compound','press','shoulders','triceps'),
('bw-handstand-pushup','Handstand Push-up','倒立撑','bodyweight','olympic','press','shoulders','triceps,core'),
('bw-inverted-row','Inverted Row','反向划船','bodyweight','compound','pull','upper-back','lats,biceps'),
('bw-bodyweight-squat','Bodyweight Squat','自重深蹲','bodyweight','compound','squat','quads','glutes'),
('bw-jump-squat','Jump Squat','跳跃深蹲','bodyweight','compound','squat','quads','glutes,calves'),
('bw-pistol-squat','Pistol Squat','单腿深蹲','bodyweight','compound','single-leg','quads','glutes,core'),
('bw-lunge-bodyweight','Bodyweight Lunge','自重箭步蹲','bodyweight','compound','single-leg','quads','glutes'),
('bw-bridge','Glute Bridge','臀桥','bodyweight','isolation','hinge','glutes','hamstrings'),
('bw-single-leg-bridge','Single-Leg Glute Bridge','单腿臀桥','bodyweight','isolation','hinge','glutes','hamstrings'),
('bw-nordic-curl','Nordic Hamstring Curl','北欧挺','bodyweight','isolation','hinge','hamstrings','calves'),
('bw-calf-raise-bodyweight','Standing Calf Raise','站姿提踵','bodyweight','isolation','squat','calves',''),
('bw-plank','Plank','平板支撑','bodyweight','isolation','core','core',''),
('bw-side-plank','Side Plank','侧平板支撑','bodyweight','isolation','core','obliques',''),
('bw-hanging-leg-raise','Hanging Leg Raise','悬垂举腿','bodyweight','isolation','core','abs','obliques'),
('bw-hanging-knee-raise','Hanging Knee Raise','悬垂屈膝举腿','bodyweight','isolation','core','abs',''),
('bw-crunch','Crunch','卷腹','bodyweight','isolation','core','abs',''),
('bw-burpee','Burpee','波比跳','bodyweight','olympic','full-body','quads','chest,core,shoulders');

-- ============ RESISTANCE BAND (8) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('bd-band-pull-apart','Band Pull-Apart','弹力带扩胸','band','isolation','pull','rear-delts','upper-back'),
('bd-band-face-pull','Band Face Pull','弹力带面拉','band','isolation','pull','rear-delts','upper-back'),
('bd-band-lateral-raise','Band Lateral Raise','弹力带侧平举','band','isolation','press','side-delts',''),
('bd-band-curl','Band Curl','弹力带弯举','band','isolation','pull','biceps',''),
('bd-band-pushdown','Band Triceps Pushdown','弹力带下压','band','isolation','press','triceps',''),
('bd-band-row','Band Seated Row','弹力带坐姿划船','band','compound','pull','upper-back','lats,biceps'),
('bd-band-shoulder-dislocate','Band Shoulder Dislocate','弹力带肩部环绕','band','isolation','press','shoulders',''),
('bd-band-good-morning','Band Good Morning','弹力带早安式','band','compound','hinge','hamstrings','glutes');

-- ============ CARDIO (12) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('cd-treadmill-run','Treadmill Run','跑步机跑步','cardio','cardio','cardio','quads','calves,hamstrings'),
('cd-treadmill-walk','Treadmill Walk','跑步机快走','cardio','cardio','cardio','calves','quads'),
('cd-incline-walk','Incline Treadmill Walk','坡度快走','cardio','cardio','cardio','calves','glutes,quads'),
('cd-outdoor-run','Outdoor Run','户外跑步','cardio','cardio','cardio','quads','calves'),
('cd-cycling','Stationary Cycling','动感单车','cardio','cardio','cardio','quads','glutes,calves'),
('cd-rowing','Rowing Machine','划船机','cardio','cardio','cardio','upper-back','lats,quads,glutes'),
('cd-elliptical','Elliptical','椭圆机','cardio','cardio','cardio','quads','glutes,calves'),
('cd-stair-climber','Stair Climber','爬楼机','cardio','cardio','cardio','glutes','quads,calves'),
('cd-jump-rope','Jump Rope','跳绳','cardio','cardio','cardio','calves','quads,shoulders'),
('cd-assault-bike','Assault Bike','风阻单车','cardio','cardio','cardio','quads','shoulders,core'),
('cd-swimming','Swimming','游泳','cardio','cardio','cardio','lats','shoulders,core'),
('cd-arc-trainer','Arc Trainer','弧步训练机','cardio','cardio','cardio','quads','glutes,calves');

-- ============ STRETCHING (10) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('st-hamstring-stretch','Hamstring Stretch','腘绳肌拉伸','stretch','stretch','hinge','hamstrings',''),
('st-quad-stretch','Quad Stretch','股四头肌拉伸','stretch','stretch','squat','quads',''),
('st-hip-flexor-stretch','Hip Flexor Stretch','髋屈肌拉伸','stretch','stretch','hinge','hip-flexors','quads'),
('st-glute-stretch','Glute Stretch','臀部拉伸','stretch','stretch','hinge','glutes',''),
('st-calf-stretch','Calf Stretch','小腿拉伸','stretch','stretch','squat','calves',''),
('st-chest-stretch','Chest Doorway Stretch','门框胸部拉伸','stretch','stretch','press','chest','front-delts'),
('st-lat-stretch','Lat Stretch','背阔肌拉伸','stretch','stretch','pull','lats',''),
('st-shoulder-stretch','Cross-Body Shoulder Stretch','肩部拉伸','stretch','stretch','press','shoulders',''),
('st-childs-pose','Childs Pose','婴儿式','stretch','stretch','core','lower-back',''),
('st-cat-cow','Cat-Cow','猫牛式','stretch','stretch','core','lower-back','abs');

-- ============ CORE / OLYMPIC ACCESSORY (5) ============
INSERT OR IGNORE INTO exercises (slug, name_en, name_zh, equipment, category, pattern, primary_muscles, secondary_muscles) VALUES
('bb-hang-power-clean','Barbell Hang Power Clean','杠铃悬垂高翻','barbell','olympic','hinge','upper-back','quads,glutes,forearms'),
('bb-clean-pull','Barbell Clean Pull','杠铃翻拉','barbell','olympic','hinge','upper-back','glutes,hamstrings'),
('bb-snatch-pull','Barbell Snatch Pull','杠铃抓举拉','barbell','olympic','hinge','upper-back','glutes,hamstrings'),
('bb-overhead-squat','Barbell Overhead Squat','杠铃过头深蹲','barbell','compound','squat','quads','shoulders,core'),
('bb-muscle-snatch','Barbell Muscle Snatch','杠铃力量抓举','barbell','olympic','full-body','shoulders','quads,upper-back');

